steps:
# Step 1: Access secrets and store them in files
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - -c
    - |
      gcloud secrets versions access latest --secret="FIREBASE_API_KEY" --project="$PROJECT_ID" > /workspace/firebase_api_key.txt
      gcloud secrets versions access latest --secret="GOOGLE_AI_API_KEY" --project="$PROJECT_ID" > /workspace/google_ai_api_key.txt

# Step 2: Build the Docker image with secrets
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_API_KEY=$(cat /workspace/firebase_api_key.txt)'
    - '--build-arg'
    - 'GOOGLE_AI_API_KEY=$(cat /workspace/google_ai_api_key.txt)'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=gen-lang-client-0637093427.firebaseapp.com'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=gen-lang-client-0637093427'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=gen-lang-client-0637093427.firebasestorage.app'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=200280322925'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:200280322925:web:d93f0f3b70c4f59211e064'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-XCLS8JGY2G'
    - '-t'
    - 'gcr.io/$PROJECT_ID/medvault'
    - '.'

# Step 3: Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/medvault']

# Step 4: Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'medvault'
    - '--image'
    - 'gcr.io/$PROJECT_ID/medvault'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=gen-lang-client-0637093427.firebaseapp.com,NEXT_PUBLIC_FIREBASE_PROJECT_ID=gen-lang-client-0637093427,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=gen-lang-client-0637093427.firebasestorage.app,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=200280322925,NEXT_PUBLIC_FIREBASE_APP_ID=1:200280322925:web:d93f0f3b70c4f59211e064,NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-XCLS8JGY2G'

images:
- 'gcr.io/$PROJECT_ID/medvault' 